### PR TITLE
Stop tailing by default

### PR DESCRIPTION
**Pull request by jgrund**
Our chroma-agent.log is currently getting tailed to the last 10MB.

Update the default so it doesn't tail and add an override to the plugin.

In addition add the yum plugin to iml-diagnostics.

### CODE REVIEW

**Comment by brianjmurrell** [comment]
The problem is that I'm looking at just one chroma-agent log file that is 96MB.  we are going to fill up jenkins pretty quickly with lots of artifacts that big (and yes, disk is cheap -- the implementation of cheap disk is not).

Can we ask for files to be compressed in SOS reports?

**Comment by jgrund** [comment]
Do we need to even explode the files in Jenkins? What advantage does that have?

**Comment by tanabarr** [comment]
while not an exciting task , we should at some point review what is getting logged, there is a significant amount of logging that I expect is not of much use to anyone

**Comment by brianjmurrell** [comment]
> Do we need to even explode the files in Jenkins? What advantage does that have?

It allows one to download smaller files than the single big file, assuming the individual files are compressed on explosion also.

Not sure about anyone else, but my VPN connection is slow enough that I don't want to have to download whole (relatively big, even compressed) SOS reports when I might only want a small file or two from it.

**Pull request merged**
